sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.1
gemfile:
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
matrix:
  exclude:
  - rvm: 2.3.1
    gemfile: gemfiles/activerecord_4.2.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/activerecord_4.2.gemfile
before_install: gem install bundler -v 1.15.1
script: "bundle exec rspec"
